package fr.pierrehb.other;

public interface Actions {
	public static enum actions {NONE,STATE,ATTAQUE1,ATTAQUE2,ATTAQUE3,ATTAQUE4,ATTAQUE5,CLOSEALLIE,FARALLIE,
			CLOSEENNEMIE,FARENNEMIE,ESQUIVEPARTICLE,ESQUIVEENNEMIE};
}
